# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [8]:
a = np.zeros((2,2)) # 모든 값이 0인 2x2 array 생성
print(a)
b = np.ones((1,2)) # 모든 값이 1인 1x2 array 생성
print(b)
c = np.full((2,2), 7) # 모든 값이 7인 2x2 array 생성
print(c)
d = np.eye(2) # 2x2 단위행렬(Identity matrix) 생성
print(d)
e = np.random.random((2,2)) # 0~1 랜덤 값을 가지는 2x2 array 생성
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.02019961 0.36379679]
 [0.37890743 0.46417081]]


In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 첫번째 행의 처음부터 2 앞까지(0,1), 두번째 행에서
# 1부터 3 앞까지(1,2)의 값들을 떠와 b에 할당.
# 따라서 b 는 다음과 같은 2x2 array:
# [[2 3]
# [6 7]]
b = a[:2, 1:3]
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
# Slicing을 한다고 해서 값을 복사해가는 것이 아니므로
# 값의 변화가 동시에 일어남

2
77


In [18]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

# 두 번째 행의 값들을 모두 가져오는 두 가지 방법
row_r1 = a[1, :]
# 1차원 행렬 (4,)
row_r2 = a[1:2, :] # 2차원 행렬 (1x4) – 기존 차원 유지/ 잘라오는 형태
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
# 두 번째 열의값들을 모두 가져오는 두 가지 방법
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape) #열 뽑을 때 더 좋음

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [22]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([a[0, 0], a[1, 1], a[2, 0]])
print(b, b.shape)
c = a[[0, 1, 2], [0, 1, 0]]
print(c, c.shape) #행, 열에 대한 인덱스 값


[1 4 5] (3,)
[1 4 5] (3,)


In [26]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

b = np.array([0, 2, 0, 1])

print(a[np.arange(4), b]) # [1 6 7 11]
a[np.arange(4), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [28]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [30]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [31]:
v = np.array([9, 10])
w = np.array([11, 12])

print(v. dot(w))
print(np.dot(v, w))

219
219


In [32]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [33]:
# 매트릭스 / 벡터 곱; [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [34]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
# 모든 원소의 합
print(np.sum(x, axis=0)) # 각 열의 합
print(np.sum(x, axis=1)) # 각 행의 합

10
[4 6]
[3 7]


In [38]:
a = np.ones( (2,3,4))
print(np.sum(a))

print(np.sum(a, axis = 0))
print(np.sum(a, axis = 1))

24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [39]:
x = np.array([[1, 2], [3, 4]])

print(x)
print(x.T)

v = np.array([1,2,3]) # 벡터는 전치 안됨
print(v)

print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


# Broadcasting

In [41]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
y = np.empty_like(x) # x와 같은 shape의 빈 매트릭스 만들기

# x의 각 행에 v와 elementwise 합을 하여 y의 해당 행에 할당
for i in range(4): #x.shape[0]
    y[i, :] = x[i, :] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [44]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])
vv = np.tile(v, (4, 1)) # v 내용을 4x1의 각 행에 반복함

print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [47]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])

y = x + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [49]:
a = np.array([1,2,3])
a1 = a.reshape([3,1]) #(3,)을 (3,1)로 변경
print(a1.shape)
a2 = a[:,None]
print(a2.shape)

(3, 1)
(3, 1)


# 연습문제2

In [52]:
a = np.array([[1,1], [2,1]])
b = np.array([15,25]).reshape([2,1])
print(np.linalg.inv(a).dot(b)) # 역행렬 np.linalg.inv

[[10.]
 [ 5.]]


# Pickle
데이터 타입 변경없이 그대로 오픈