# lab 05 Logistic Classification

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [3]:
X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([2,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X, W)+b)

cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

In [4]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost,train], feed_dict = {X: x_data, Y:y_data})
        if step%200 ==0:
            print(step, cost_val)
            
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict = {X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect(Y): ", c, "\nAccuracy: ", a)

0 1.8588897
200 0.7862256
400 0.56168854
600 0.4714398
800 0.4282863
1000 0.40248498
1200 0.38404492
1400 0.36919236
1600 0.3563325
1800 0.34472665
2000 0.33400595
2200 0.3239718
2400 0.31450975
2600 0.30554786
2800 0.29703686
3000 0.28893986
3200 0.28122774
3400 0.27387515
3600 0.26686004
3800 0.26016256
4000 0.253764
4200 0.2476474
4400 0.24179666
4600 0.2361968
4800 0.23083395
5000 0.22569476
5200 0.2207671
5400 0.21603924
5600 0.21150045
5800 0.2071405
6000 0.20294993
6200 0.1989197
6400 0.1950415
6600 0.19130743
6800 0.18771012
7000 0.18424268
7200 0.18089856
7400 0.17767154
7600 0.17455606
7800 0.17154664
8000 0.16863815
8200 0.16582586
8400 0.16310523
8600 0.160472
8800 0.15792231
9000 0.1554523
9200 0.1530584
9400 0.1507372
9600 0.14848563
9800 0.14630066
10000 0.14417936

Hypothesis:  [[0.0285363 ]
 [0.1557493 ]
 [0.29413864]
 [0.78632617]
 [0.9426478 ]
 [0.98120475]] 
Correct(Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


In [5]:
xy = np.loadtxt('DeepLearningZeroToAll-master/data-03-diabetes.csv', delimiter = ',', dtype = np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [6]:
X = tf.placeholder(tf.float32, shape = [None, 8])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([8,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X,W) + b)
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

predicted = tf.cast(hypothesis>0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step %200 ==0:
            print(step, sess.run(cost, feed_dict = feed))
    
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print("\nHypothesis: ", h, "\nCorrect(Y): ", c, "\nAccuracy: ", a)

0 0.73231286
200 0.5559278
400 0.52866495
600 0.5214396
800 0.51752293
1000 0.51438916
1200 0.5115966
1400 0.50904745
1600 0.50670624
1800 0.5045505
2000 0.50256205
2200 0.5007251
2400 0.49902543
2600 0.49745077
2800 0.49598974
3000 0.4946325
3200 0.49337018
3400 0.49219465
3600 0.49109864
3800 0.49007577
4000 0.4891201
4200 0.48822635
4400 0.4873896
4600 0.48660564
4800 0.48587033
5000 0.48518005
5200 0.48453164
5400 0.48392195
5600 0.48334822
5800 0.48280793
6000 0.48229885
6200 0.4818187
6400 0.48136565
6600 0.48093784
6800 0.48053357
7000 0.48015133
7200 0.47978964
7400 0.47944736
7600 0.47912306
7800 0.47881576
8000 0.47852427
8200 0.47824785
8400 0.4779854
8600 0.47773618
8800 0.4774993
9000 0.47727412
9200 0.4770599
9400 0.47685608
9600 0.4766622
9800 0.47647735
10000 0.47630128

Hypothesis:  [[0.3957755 ]
 [0.93420386]
 [0.2317743 ]
 [0.94262075]
 [0.15471676]
 [0.7825824 ]
 [0.9401607 ]
 [0.5915066 ]
 [0.22149494]
 [0.5402867 ]
 [0.7128022 ]
 [0.1607959 ]
 [0.28222102]
 [0.254

# lab 06 Softmax Classification

In [7]:
x_data= [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict= {X:x_data, Y:y_data})
        if step%200 == 0:
            print(step, sess.run(cost, feed_dict = {X: x_data, Y: y_data}))
    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))
        


0 8.414217
200 0.65463257
400 0.54534787
600 0.45133916
800 0.36068386
1000 0.27280414
1200 0.230899
1400 0.21000385
1600 0.19243923
1800 0.17747521
2000 0.16458377
--------------
[[3.2684024e-02 9.6730608e-01 9.9438948e-06]] [1]
--------------
[[0.67285097 0.2973502  0.02979887]] [0]
--------------
[[1.7489613e-08 4.0298089e-04 9.9959701e-01]] [2]
--------------
[[3.2684054e-02 9.6730608e-01 9.9438848e-06]
 [6.7285097e-01 2.9735020e-01 2.9798875e-02]
 [1.7489613e-08 4.0298089e-04 9.9959701e-01]] [1 0 2]


# 06-2 Fancy Softmax Classification

In [8]:
xy = np.loadtxt('DeepLearningZeroToAll-master/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [13]:
X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6

Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("one_hot:", Y_one_hot)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape one_hot:", Y_one_hot)

'''
one_hot: Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape:0", shape=(?, 7), dtype=float32)
'''

W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/loss
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                                 labels=tf.stop_gradient([Y_one_hot])))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2000):
        sess.run(optimizer, feed_dict = {X: x_data, Y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={X:x_data, Y:y_data})
            print ("Step: {:5}\tLoss: {:3f}\tAcc: {:.2%}".format(step, loss, acc))
            
    pred = sess.run(prediction, feed_dict = {X: x_data})
    
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p==int(y), p, int(y)))

one_hot: Tensor("one_hot_4:0", shape=(?, 1, 7), dtype=float32)
reshape one_hot: Tensor("Reshape_4:0", shape=(?, 7), dtype=float32)
Step:     0	Loss: 4.482080	Acc: 14.85%
Step:   100	Loss: 0.612605	Acc: 80.20%
Step:   200	Loss: 0.383739	Acc: 89.11%
Step:   300	Loss: 0.282933	Acc: 93.07%
Step:   400	Loss: 0.225934	Acc: 95.05%
Step:   500	Loss: 0.188747	Acc: 96.04%
Step:   600	Loss: 0.162239	Acc: 96.04%
Step:   700	Loss: 0.142244	Acc: 96.04%
Step:   800	Loss: 0.126574	Acc: 98.02%
Step:   900	Loss: 0.113955	Acc: 99.01%
Step:  1000	Loss: 0.103582	Acc: 99.01%
Step:  1100	Loss: 0.094912	Acc: 99.01%
Step:  1200	Loss: 0.087568	Acc: 100.00%
Step:  1300	Loss: 0.081273	Acc: 100.00%
Step:  1400	Loss: 0.075822	Acc: 100.00%
Step:  1500	Loss: 0.071059	Acc: 100.00%
Step:  1600	Loss: 0.066863	Acc: 100.00%
Step:  1700	Loss: 0.063141	Acc: 100.00%
Step:  1800	Loss: 0.059817	Acc: 100.00%
Step:  1900	Loss: 0.056831	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 