# lab 05 Logistic Classification

In [9]:
import tensorflow as tf
import numpy as np

In [4]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [7]:
X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([2,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X, W)+b)

cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost,train], feed_dict = {X: x_data, Y:y_data})
        if step%200 ==0:
            print(step, cost_val)
            
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict = {X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect(Y): ", c, "\nAccuracy: ", a)

0 1.2017071
200 0.52510285
400 0.4843136
600 0.4577388
800 0.4374772
1000 0.42044613
1200 0.40531
1400 0.39143857
1600 0.37851164
1800 0.36635372
2000 0.3548608
2200 0.3439653
2400 0.3336185
2600 0.3237823
2800 0.31442443
3000 0.30551672
3200 0.29703292
3400 0.28894892
3600 0.2812421
3800 0.27389097
4000 0.26687565
4200 0.26017705
4400 0.25377718
4600 0.24765909
4800 0.24180704
5000 0.23620622
5200 0.23084229
5400 0.22570239
5600 0.22077404
5800 0.21604566
6000 0.21150641
6200 0.20714606
6400 0.20295513
6600 0.19892456
6800 0.19504623
7000 0.19131194
7200 0.18771438
7400 0.18424678
7600 0.1809024
7800 0.17767529
8000 0.17455964
8200 0.17155005
8400 0.16864143
8600 0.16582902
8800 0.16310827
9000 0.16047502
9200 0.15792519
9400 0.15545504
9600 0.15306102
9800 0.15073968
10000 0.14848809

Hypothesis:  [[0.03031754]
 [0.15826975]
 [0.3028389 ]
 [0.7823103 ]
 [0.94015867]
 [0.9803649 ]] 
Correct(Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


In [11]:
xy = np.loadtxt('DeepLearningZeroToAll-master/data-03-diabetes.csv', delimiter = ',', dtype = np.float32)

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [15]:
X = tf.placeholder(tf.float32, shape = [None, 8])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([8,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X,W) + b)
cost = -tf.reduce_mean(Y*tf.log(hypothesis) + (1-Y)*tf.log(1-hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

predicted = tf.cast(hypothesis>0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    feed = {X: x_data, Y: y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step %200 ==0:
            print(step, sess.run(cost, feed_dict = feed))
    
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print("\nHypothesis: ", h, "\nCorrect(Y): ", c, "\nAccuracy: ", a)

0 1.0775934
200 0.7388337
400 0.67895454
600 0.65681976
800 0.6412197
1000 0.6277597
1200 0.61566365
1400 0.6047108
1600 0.594776
1800 0.58575666
2000 0.57756054
2200 0.57010436
2400 0.5633129
2600 0.55711824
2800 0.5514596
3000 0.54628295
3200 0.54153967
3400 0.5371867
3600 0.53318566
3800 0.5295024
4000 0.52610654
4200 0.5229708
4400 0.5200711
4600 0.5173859
4800 0.5148957
5000 0.51258326
5200 0.51043314
5400 0.5084313
5600 0.5065653
5800 0.5048237
6000 0.5031965
6200 0.50167435
6400 0.50024897
6600 0.49891287
6800 0.49765903
7000 0.4964814
7200 0.49537408
7400 0.49433202
7600 0.49335048
7800 0.4924251
8000 0.49155203
8200 0.49072748
8400 0.4899482
8600 0.4892112
8800 0.4885135
9000 0.48785263
9200 0.4872262
9400 0.48663196
9600 0.48606795
9800 0.48553205
10000 0.48502275

Hypothesis:  [[0.39136222]
 [0.91613823]
 [0.19013086]
 [0.93820715]
 [0.13448396]
 [0.7409643 ]
 [0.9360809 ]
 [0.599184  ]
 [0.23624772]
 [0.5377309 ]
 [0.7292745 ]
 [0.17987639]
 [0.19843948]
 [0.24976274]
 [0.7

# lab 06 Softmax Classification

In [30]:
x_data= [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W)+b)

cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict= {X:x_data, Y:y_data})
        if step%200 == 0:
            print(step, sess.run(cost, feed_dict = {X: x_data, Y: y_data}))
    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))
        


0 4.8480997
200 0.54636586
400 0.45340627
600 0.38012353
800 0.31055906
1000 0.24178606
1200 0.21589087
1400 0.19710973
1600 0.18123353
1800 0.16764417
2000 0.15588842
--------------
[[9.0882536e-03 9.9090040e-01 1.1342816e-05]] [1]
--------------
[[0.8041279  0.16546802 0.0304041 ]] [0]
--------------
[[1.4274465e-08 3.5179307e-04 9.9964821e-01]] [2]
--------------
[[9.0882536e-03 9.9090040e-01 1.1342816e-05]
 [8.0412799e-01 1.6546790e-01 3.0404063e-02]
 [1.4274465e-08 3.5179307e-04 9.9964821e-01]] [1 0 2]
